/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.labels.StandardCrosshairLabelGenerator;
import org.jfree.chart.plot.XYPlot;

/**
 *
 * @author mathe
 */
public class ChartView extends javax.swing.JFrame {

    /**
     * Creates new form ChartView
     */
    public ChartView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        standardCrosshairLabelGenerator1 = new org.jfree.chart.labels.StandardCrosshairLabelGenerator();
        xYPlot1 = new org.jfree.chart.plot.XYPlot();
        jLabel1 = new javax.swing.JLabel();
        checkBoxTituloGrafico = new javax.swing.JCheckBox();
        checkBoxLegenda = new javax.swing.JCheckBox();
        checkBoxTituloEixos = new javax.swing.JCheckBox();
        checkBoxRotuloDadosPorcento = new javax.swing.JCheckBox();
        checkBoxRotuloValores = new javax.swing.JCheckBox();
        checkBoxRotuloPorcento = new javax.swing.JCheckBox();
        checkBoxCorIndividual = new javax.swing.JCheckBox();
        checkBoxCorGrupo = new javax.swing.JCheckBox();
        checkBoxGrade = new javax.swing.JCheckBox();
        buttonFechar = new javax.swing.JButton();
        buttonPadrao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxGraficoBase = new javax.swing.JComboBox<>();
        panelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gráfico");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Elementos gráficos");

        checkBoxTituloGrafico.setText("Título");
        checkBoxTituloGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTituloGraficoActionPerformed(evt);
            }
        });

        checkBoxLegenda.setText("Legenda");

        checkBoxTituloEixos.setText("Título dos eixos");

        checkBoxRotuloDadosPorcento.setText("Rótulo de Dados (%)");

        checkBoxRotuloValores.setText("Rótulo de Dados - Valor");

        checkBoxRotuloPorcento.setText("Rótulo de Dados - Valor (%)");

        checkBoxCorIndividual.setText("Cor das Barras");

        checkBoxCorGrupo.setText("Cor das Barras (por grupo)");

        checkBoxGrade.setText("Grade");

        buttonFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonFechar.setText("Fechar");

        buttonPadrao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPadrao.setText("Restaurar padrão");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Gráfico padrão");

        comboBoxGraficoBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxGraficoBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barras Horizontais", "Barras Verticais" }));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxGrade)
                            .addComponent(checkBoxCorGrupo)
                            .addComponent(checkBoxCorIndividual)
                            .addComponent(checkBoxRotuloPorcento)
                            .addComponent(checkBoxRotuloValores)
                            .addComponent(checkBoxRotuloDadosPorcento)
                            .addComponent(checkBoxTituloEixos)
                            .addComponent(checkBoxLegenda)
                            .addComponent(checkBoxTituloGrafico)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(521, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonPadrao)
                                .addGap(18, 18, 18)
                                .addComponent(buttonFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxGraficoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxGraficoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxTituloGrafico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxLegenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxTituloEixos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxRotuloDadosPorcento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxRotuloValores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxRotuloPorcento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxCorIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxCorGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxGrade))
                    .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonPadrao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxTituloGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxTituloGraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxTituloGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartView().setVisible(true);
            }
        });
    }

    public JButton getButtonFechar() {
        return buttonFechar;
    }

    public JButton getButtonPadrao() {
        return buttonPadrao;
    }

    public JCheckBox getCheckBoxCorGrupo() {
        return checkBoxCorGrupo;
    }

    public JCheckBox getCheckBoxCorIndividual() {
        return checkBoxCorIndividual;
    }

    public JCheckBox getCheckBoxGrade() {
        return checkBoxGrade;
    }

    public JCheckBox getCheckBoxLegenda() {
        return checkBoxLegenda;
    }

    public JCheckBox getCheckBoxRotuloDadosPorcento() {
        return checkBoxRotuloDadosPorcento;
    }

    public JCheckBox getCheckBoxRotuloPorcento() {
        return checkBoxRotuloPorcento;
    }

    public JCheckBox getCheckBoxRotuloValores() {
        return checkBoxRotuloValores;
    }

    public JCheckBox getCheckBoxTituloEixos() {
        return checkBoxTituloEixos;
    }

    public JCheckBox getCheckBoxTituloGrafico() {
        return checkBoxTituloGrafico;
    }

    public JComboBox<String> getComboBoxGraficoBase() {
        return comboBoxGraficoBase;
    }

    public JPanel getPanelGrafico() {
        return panelGrafico;
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonPadrao;
    private javax.swing.JCheckBox checkBoxCorGrupo;
    private javax.swing.JCheckBox checkBoxCorIndividual;
    private javax.swing.JCheckBox checkBoxGrade;
    private javax.swing.JCheckBox checkBoxLegenda;
    private javax.swing.JCheckBox checkBoxRotuloDadosPorcento;
    private javax.swing.JCheckBox checkBoxRotuloPorcento;
    private javax.swing.JCheckBox checkBoxRotuloValores;
    private javax.swing.JCheckBox checkBoxTituloEixos;
    private javax.swing.JCheckBox checkBoxTituloGrafico;
    private javax.swing.JComboBox<String> comboBoxGraficoBase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelGrafico;
    private org.jfree.chart.labels.StandardCrosshairLabelGenerator standardCrosshairLabelGenerator1;
    private org.jfree.chart.plot.XYPlot xYPlot1;
    // End of variables declaration//GEN-END:variables
}
